# Generated by Django 6.0.3 on 2026-04-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caption',
            options={'ordering': ['-confidence_score']},
        ),
        migrations.AlterField(
            model_name='caption',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
