# Generated by Django 6.0.3 on 2026-04-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_caption_options_alter_caption_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestore',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='imagestore',
            name='image_file',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='gallery/', width_field='width'),
        ),
        migrations.AlterField(
            model_name='imagestore',
            name='source',
            field=models.CharField(choices=[('HUMAN', 'Uploaded'), ('AI', 'Generated'), ('WEB', 'Internet')], default='HUMAN', max_length=10),
        ),
    ]
